name: Publish PHP 8.4 (Latest) image to Docker Hub
on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "README.md"
      - "CHANGELOG.md"
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: drnxloc/nginx-php-fpm
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest"
